### ISSUE TITLE
Misskey「HQ」の変更

### ISSUE THREAD

**Issue by 4ioskd** [Xeltica/MisskeyTools#52]
Misskey HQは過去の名称のため、Misskey-dev(正式名称はMisskey Development Division)もしくはMisskey Projectに変更した方が良いかと思われます。変数 disclaimerForMisskey「Hq」 も同時に変えた方が良いかと。

変更対象と思われるコード：
https://github.com/Xeltica/MisskeyTools/blob/288c594f278da88cb85ac419711815783dcab469/src/frontend/langs/ja-JP.json#L41
https://github.com/Xeltica/MisskeyTools/blob/db99944d686d8342a1a8efe6993842e78ef02d29/src/frontend/App.tsx#L71

**Comment by Xeltica** [comment]
Misskey開発チームの正式名称について、後日正式に確認取った上で変更いたします。

なお、変数は既存の翻訳が破棄されるリスクがあるため、ルールとして変更しない方針でいます（要明文化）

**Comment by Xeltica** [comment]
方針: 「Misskey Development Division」に置き換える
